sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          packages:
            - cmake
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
    - os: osx
      compiler: clang

script:
  # 1. check formatting
  - ./tools/check-formatting --all
  # 2. check compilation
  - mkdir build && cd build
  - cmake ..
  - make
  - make DESTDIR="${PWD}"/staging-dir install
